# Generated by Django 5.1.6 on 2025-03-01 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DateOfBrth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='EnrollmentDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
