# Generated by Django 5.1.6 on 2025-03-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_student_dateofbrth_student_enrollmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='DateOfBrth',
            new_name='DateOfBirth',
        ),
    ]
