# Generated by Django 5.1.6 on 2025-03-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_dateofbrth_student_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
